services:
  - type: web
    name: inventory-management-system
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: inventory-db
    databaseName: inventory_management
    user: inventory_user
    region: frankfurt
    plan: free